### DATA-REST APIs based on the TutorialsRepository
GET http://{{host}}/tutorials HTTP/1.1
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### APIs coming from DATA-REST using the methods in TutorialsRepository
GET http://{{host}}/tutorials/search HTTP/1.1
Content-Type: application/json

###
GET http://{{host}}/tutorials/search/findAllPublished
Content-Type: application/json

### create new tutorial
POST http://{{host}}/tutorials HTTP/1.1
Content-Type: application/json

{
  "title": "tut20",
  "description": "tut description",
  "published": false
}