###
GET http://{{host}}/api/tutorials HTTP/1.1
Content-Type: application/json

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://{{host}}/api/tutorials/1 HTTP/1.1
Content-Type: application/json

###
GET http://{{host}}/api/tutorials/paginated?page=2&size=2 HTTP/1.1
Content-Type: application/json

### create new tutorial
POST http://{{host}}/api/tutorials HTTP/1.1
Content-Type: application/json

{
"title": "tut20",
"description": "tut description"
}

